driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: amazonlinux-2017.03
    driver:
      name: ec2
      image_id: ami-6df1e514
      aws_ssh_key_id: test-kitchen
      region: us-west-2
      availability_zone: a
      require_chef_omnibus: true
      instance_type: t2.large
      associate_public_ip: true
      interface: dns
    transport:
      username: ec2-user
      ssh_key: ~/.ssh/id_rsa
  - name: debian-9.0
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[papertrail]
    attributes:
      papertrail:
        files:
          - /tmp/test.log
          - /srv/foo.txt
          - /var/log/*.bar
          - path: /srv/foo.txt
            tag: foo_file
        exclude_files:
          - /tmp/exlude.log
          - /srv/dont-include.log
          - /var/log/skip-me.log
        hostname: 'my-super-awesome-hostname'
        exclude_patterns:
          - '\d+ things'
        destination_host: 'testhost.papertrail'
        destination_port: 6500
        destination_protocol: 'tls'
        new_file_check_interval: 30
