name             'papertrail'
maintainer       'Papertrail'
maintainer_email 'support@papertrailapp.com'
license          'MIT'
description      'Installs/Configures Papertrail\'s remote_syslog2'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url       'https://github.com/papertrail/chef-papertrail'
version          '1.0.1'
issues_url       'https://github.com/papertrail/chef-papertrail/issues'
chef_version     '>= 12'
supports 'ubuntu', '>= 14.04'
supports 'debian', '= 9'
supports 'centos', '>= 6'
supports 'redhat', '>= 6'
supports 'amazon', '= 2017.03'

depends 'yum'
depends 'yum-epel'
depends 'apt'
